language: rust

rust:
    - nightly

cache: cargo

before_script:
    - rustup component add rust-src
    - (cargo install xargo || true)

sudo: false

notifications:
    on_success: never
    on_failure: change

addons:
    apt:
        packages:
            - nasm

script:
    - make
