language: rust

rust:
    - nightly

cache:
    cargo: true
    directories:
        - $HOME/.cache/pip
        - $HOME/.rustup
        - $HOME/.xargo

before_script:
    - rustup update
    - rustup component add rust-src
    - (cargo install xargo || true)
    - pip install tap.py --user

sudo: false

notifications:
    on_success: never
    on_failure: change

addons:
    apt:
        packages:
            # building
            - nasm
            # testing
            - qemu
            - xorriso
            - python-pip

script:
    - make
    - make clean
    - make test | ./script/split_test.pl
    - ~/.local/bin/tappy test
