language: rust

rust:
    - nightly

cache: cargo

before_script:
    - (cargo install xargo || true)
    - (cargo install rustfmt || true)
    - PATH=$PATH:~/.cargo/bin

sudo: false

notifications:
    on_success: never
    on_failure: change

addons:
    apt:
        packages:
            - nasm

script: bash scripts/travis-build.sh
